spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school-management-db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create